### ISSUE TITLE
failed to download the model files

### ISSUE THREAD

**Issue by DemonDamon** [breezedeus/cnocr-models#1]
why the files could not be downloaded even I turn on the VPN

**Comment by breezedeus** [comment]
cnocr更新到 v1.2.*，应该可以下载了

**Comment by gmx1992** [comment]
百度网盘提示模型文件清空，请问如何获取

**Comment by steven-guan** [comment]
> why the files could not be downloaded even I turn on the VPN

GIT is not good at handling big binary files, if there are any connection issues such as timeout, downloading will fail.

**Comment by sixixi007** [comment]
git clone 下载不下来，百度网盘的分享取消了，请问如何获取？
